### ISSUE TITLE
isurl() returns true for arbitrary strings

### ISSUE THREAD

**Issue by trp07** [shopnilsazal/validus#10]
* validus version: 0.2.0
* Python version: 3.6
* Operating System: Linux

### Description
isurl() returns True for arbitrary strings of length 4+

### What I Did

```
>>> validus.isurl('')
False
>>> validus.isurl('a')
False
>>> validus.isurl('ab')
False
>>> validus.isurl('abc')
False
>>> validus.isurl('abcd')   # should not return true
True
```

**Comment by trp07** [comment]
I really like your package, by the way.  It's simple and easy to use.  I'm using it in a project I'm creating: https://github.com/trp07/messages

**Comment by shopnilsazal** [comment]
Hi @trp07, 
Thanks a lot for letting me know about this issue. I will look into it and will provide fix very soon.

**Comment by trp07** [comment]
Hello,
I was looking online for url regex's, and I modified this one slightly to match your use cases.  I think it'll help fix this issue.  

You can modify line 869 of **validators.py** as:

```
url = re.compile(r'^(?i)\b((?:(ftp|tcp|irc|udp|wss?|https?)://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:\'".,<>?\xab\xbb\u201c\u201d\u2018\u2019]))$')
```

I found it near the bottom of this thread: https://gist.github.com/uogbuji/705383

But I modified the beginning a bit to account for the **ftp/tcp/etc...** portion

**Comment by shopnilsazal** [comment]
I updated the `isurl` function. I removed support for irc url.
