### ISSUE TITLE
Questing: why you didn't want to use precompiled regular expressions?

### ISSUE THREAD

**Issue by pahaz** [shopnilsazal/validus#3]
As I see. You computer regular expression at call time.

It will work faster if use precompiled regular expressions.

**Comment by shopnilsazal** [comment]
Quote from official documentation:

> Using re.compile() and saving the resulting regular expression object for reuse is more efficient when the expression will be used several times in a single program.

But in this case, every expression is used only once. I thought, compiling regular expression would not make any difference.

**Comment by lwanger** [comment]
Why not create a parameter to allow the user to specify to compile it, with a default not to compile. That way they could get the efficiency if they know it's going to be used multiple times.

**Comment by shopnilsazal** [comment]
@lwanger It's a good idea. Though I am planning to refactor this with "re.compile()".
